namespace Utils
{
    public class Card
    {
        public string Object { get; set; }
        public string Id { get; set; }
        public string Oracle_Id { get; set; }
        public string Multiverse_ids { get; set; }
        public string Mtgo_Id { get; set; }
        public string Mtgo_Foil_Id { get; set; }
        public string Tcgplayer_Id { get; set; }
        public string Cardmarket_Id { get; set; }
        public string Name { get; set; }
        public string Lang { get; set; }
        public string Released_at { get; set; }
        public string Uri { get; set; }
        public string Scryfall_Uri { get; set; }
        public string Layout { get; set; }
        public string Highres_Image { get; set; }
        public string Image_Status { get; set; }
        public string Image_Uris { get; set; }
        public string Mana_Cost { get; set; }
        public string Cmc { get; set; }
        public string Type_Line { get; set; }
        public string Oracle_Text { get; set; }
        public string Power { get; set; }
        public string Toughness { get; set; }
        public string Colors { get; set; }
        public string Color_Identity { get; set; }
        public string Keywords { get; set; }
        public string Legalities { get; set; }
        public string Games { get; set; }
        public string Reserved { get; set; }
        public string Foil { get; set; }
        public string Nonfoil { get; set; }
        public string Finishes { get; set; }
        public string Oversized { get; set; }
        public string Promo { get; set; }
        public string Reprint { get; set; }
        public string Variation { get; set; }
        public string Set_Id { get; set; }
        public string Set { get; set; }
        public string Set_Name { get; set; }
        public string Set_Type { get; set; }
        public string Set_Uri { get; set; }
        public string Set_Search_Uri { get; set; }
        public string Scryfall_Set_Uri { get; set; }
        public string Rulings_Uri { get; set; }
        public string Prints_Search_Uri { get; set; }
        public string Collector_Number { get; set; }
        public string Digital { get; set; }
        public string Rarity { get; set; }
        public string Flavor_Text { get; set; }
        public string Card_Back_Id { get; set; }
        public string Artist { get; set; }
        public string Artist_Ids { get; set; }
        public string Illustration_Id { get; set; }
        public string Border_Color { get; set; }
        public string Frame { get; set; }
        public string Full_Art { get; set; }
        public string Textless { get; set; }
        public string Booster { get; set; }
        public string Story_Spotlight { get; set; }
        public string Edhrec_Rank { get; set; }
        public string Penny_Rank { get; set; }
        public string Prices { get; set; }
        public string Related_Uris { get; set; }
        public string Small { get; set; }
        public string Normal { get; set; }
        public string Large { get; set; }
        public string Png { get; set; }
        public string Art_Crop { get; set; }
        public string Border_crop { get; set; }
        public string Standard { get; set; }
        public string Future { get; set; }
        public string Historic { get; set; }
        public string Gladiator { get; set; }
        public string Pioneer { get; set; }
        public string Explorer { get; set; }
        public string Modern { get; set; }
        public string Legacy { get; set; }
        public string Pauper { get; set; }
        public string Vintage { get; set; }
        public string Penny { get; set; }
        public string Commander { get; set; }
        public string Brawl { get; set; }
        public string Historicbrawl { get; set; }
        public string Alchemy { get; set; }
        public string Paupercommander { get; set; }
        public string Duel { get; set; }
        public string Oldschool { get; set; }
        public string Premodern { get; set; }
        public double Usd { get; set; }
        public double Usd_Foil { get; set; }
        public double Usd_Etched { get; set; }
        public double Eur { get; set; }
        public double Eur_Foil { get; set; }
        public double Tix { get; set; }
        public string Gatherer { get; set; }
        public string Tcgplayer_Infinite_Articles { get; set; }
        public string Tcgplayer_Infinite_Decks { get; set; }
        public string Edhrec { get; set; }
    }


}